# Generated by Django 4.1.11 on 2023-10-26 15:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('element_equipment', wagtail.fields.StreamField([('eqipment_cards', wagtail.blocks.StructBlock([('name_equipment', wagtail.blocks.RichTextBlock(features=['link', 'h5'], help_text='название оборудования', required=True)), ('pfoto_equipment', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description_equipment', wagtail.blocks.RichTextBlock(help_text='краткое описание оборудование', max_length=255, required=True)), ('characteristic_equipment', wagtail.blocks.TextBlock(help_text='характеристики оборудования', max_length=255, required=True)), ('price_equipment', wagtail.blocks.TextBlock(help_text='цена', required=True)), ('promou_equipment', wagtail.blocks.TextBlock(help_text='продвижение', required=False))]))], blank=True, use_json_field=True)),
                ('diskription_equipment', wagtail.fields.StreamField([('title_equipments', wagtail.blocks.StructBlock([('title_diskription_equipment', wagtail.blocks.RichTextBlock(features=['link', 'h2'], help_text='заголовок', required=True)), ('podsagolovok', wagtail.blocks.RichTextBlock(help_text='подзаголовок на странице с оборудованием', required=True))]))], blank=True, use_json_field=True)),
                ('promote_keywords', models.TextField(blank=True, verbose_name='promote_keywords')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
