# Generated by Django 4.2.7 on 2023-11-17 14:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='element_equipment',
            field=wagtail.fields.StreamField([('eqipment_cards', wagtail.blocks.StructBlock([('name_equipment', wagtail.blocks.TextBlock(help_text='заголовок карточки с оборудованием', max_length=255, required=True)), ('pfoto_equipment', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description_equipment', wagtail.blocks.RichTextBlock(help_text='Брэнд', max_length=255, required=True)), ('characteristic_equipment', wagtail.blocks.RichTextBlock(help_text='Характеристики', required=True)), ('price_equipment', wagtail.blocks.TextBlock(help_text='цена', required=True)), ('promou_equipment', wagtail.blocks.TextBlock(help_text='Продвижение', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
