# Generated by Django 4.2.7 on 2025-12-12 09:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_list', '0005_alter_equipmentlist_element_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='element_equipment',
            field=wagtail.fields.StreamField([('eqipment_cards', wagtail.blocks.StructBlock([('name_equipment', wagtail.blocks.TextBlock(help_text='заголовок карточки с оборудованием', max_length=255, required=True)), ('pfoto_equipment', wagtail.images.blocks.ImageChooserBlock(required=True)), ('smallname_equipment', wagtail.blocks.TextBlock(help_text='заголовок карточки с оборудованием в одно слово', max_length=255, required=False)), ('description_equipment', wagtail.blocks.RichTextBlock(help_text='Брэнд', max_length=255, required=True)), ('characteristic_equipment', wagtail.blocks.RichTextBlock(help_text='Характеристики', required=True)), ('price_equipment', wagtail.blocks.DecimalBlock(decimal_places=2, help_text='цена (числовое значение)', max_digits=10, min_value=0, required=True)), ('discount_percent', wagtail.blocks.DecimalBlock(decimal_places=2, help_text='скидка в процентах для этого товара (0-100)', max_digits=5, max_value=100, min_value=0, required=False)), ('youtube_link', wagtail.blocks.URLBlock(help_text='ссылка на ютуб', required=False)), ('promou_equipment', wagtail.blocks.TextBlock(help_text='Продвижение', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
