# Generated by Django 4.2.7 on 2026-01-04 14:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_list', '0009_alter_equipmentlist_element_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='element_equipment',
            field=wagtail.fields.StreamField([('eqipment_cards', wagtail.blocks.StructBlock([('name_equipment', wagtail.blocks.TextBlock(help_text='заголовок карточки с оборудованием', max_length=255, required=True)), ('pfoto_equipment', wagtail.images.blocks.ImageChooserBlock(required=True)), ('additional_photo_1', wagtail.images.blocks.ImageChooserBlock(help_text='Дополнительное фото 1', required=False)), ('additional_photo_2', wagtail.images.blocks.ImageChooserBlock(help_text='Дополнительное фото 2', required=False)), ('additional_photo_3', wagtail.images.blocks.ImageChooserBlock(help_text='Дополнительное фото 3', required=False)), ('smallname_equipment', wagtail.blocks.TextBlock(help_text='заголовок карточки с оборудованием в одно слово', max_length=255, required=False)), ('description_equipment', wagtail.blocks.RichTextBlock(help_text='Брэнд', max_length=255, required=True)), ('characteristic_equipment', wagtail.blocks.RichTextBlock(help_text='Характеристики', required=True)), ('price_equipment', wagtail.blocks.TextBlock(help_text='цена (числовое значение, например: 100.50 или 100)', required=True)), ('discount_percent', wagtail.blocks.TextBlock(help_text='скидка в процентах для этого товара (0-100, например: 10 или 15.5)', required=False)), ('quantity_available', wagtail.blocks.IntegerBlock(default=0, help_text='количество доступных товаров (0 - товар недоступен)', min_value=0, required=False)), ('youtube_link', wagtail.blocks.URLBlock(help_text='ссылка на ютуб', required=False)), ('promou_equipment', wagtail.blocks.TextBlock(help_text='Продвижение', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
