# Generated by Django 4.2.7 on 2026-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_list', '0010_alter_equipmentlist_element_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='promote_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='promote_keywords'),
        ),
    ]
