# Generated by Django 4.1.11 on 2023-10-26 15:57

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_snipet_carusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_band', models.URLField(blank=True, help_text='ссылка на группу', null=True)),
                ('pfoto_in_carusel', models.ImageField(upload_to='carusel/')),
                ('interval', models.IntegerField(blank=True, help_text='интервал переключения', null=True)),
            ],
            options={
                'verbose_name': 'контент карусели в фУтере',
                'verbose_name_plural': 'данные карусели',
            },
        ),
        migrations.CreateModel(
            name='Footer_snipet_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_contact_data', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'контактные данные в фУтере',
                'verbose_name_plural': 'контактные данные',
            },
        ),
        migrations.CreateModel(
            name='PortnerUrlFuter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_potner_page', models.URLField(blank=True, null=True)),
                ('text_link_portner', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_discript_portner', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'потнера в футере',
                'verbose_name_plural': 'Портнеры',
            },
        ),
        migrations.CreateModel(
            name='UrlFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_posicion', models.URLField(blank=True, null=True)),
                ('text_link', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_discript', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'полезная ссылка в футере',
                'verbose_name_plural': 'полезные ссылки',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='menucards1',
            field=wagtail.fields.StreamField([('cards_fild', wagtail.blocks.StructBlock([('external_url', wagtail.blocks.RichTextBlock(features=['link', 'h4'], label='ссылка на страницу с оборудованием', required=False)), ('title', wagtail.blocks.CharBlock(features=['link', 'h4'], help_text='заголовок', required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('discription', wagtail.blocks.RichTextBlock(help_text='описание', required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promote_keywords',
            field=models.TextField(blank=True, verbose_name='promote_keywords'),
        ),
    ]
