# Generated by Django 4.1.11 on 2023-10-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_footer_snipet_carusel_footer_snipet_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_snipet_contact',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='footer_snipet_contact',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
