# Generated by Django 4.1.11 on 2023-10-27 06:27

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footer_snipet_contact_locale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='menucards1',
            field=wagtail.fields.StreamField([('cards_fild', wagtail.blocks.StructBlock([('external_url', wagtail.blocks.RichTextBlock(features=['link', 'h4'], label='ссылка на страницу с оборудованием', required=False)), ('title', wagtail.blocks.CharBlock(features=['link', 'h4'], help_text='заголовок', required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('discription', wagtail.blocks.RichTextBlock(help_text='описание', required=False))]))], blank=True, use_json_field=True, verbose_name='Карточка меню'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promote_keywords',
            field=models.TextField(blank=True, verbose_name='Ключевые слова'),
        ),
    ]
