# Generated by Django 4.1.11 on 2023-10-27 07:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_menucards1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_snipet_carusel',
            options={'verbose_name': 'контент карусели в футере', 'verbose_name_plural': 'данные карусели'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='menucards_en',
            field=wagtail.fields.StreamField([('cards_fild', wagtail.blocks.StructBlock([('external_url', wagtail.blocks.RichTextBlock(features=['link', 'h4'], label='ссылка на страницу с оборудованием', required=False)), ('title', wagtail.blocks.CharBlock(features=['link', 'h4'], help_text='заголовок', required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('discription', wagtail.blocks.RichTextBlock(help_text='описание', required=False))]))], blank=True, use_json_field=True, verbose_name='Карточка меню'),
        ),
    ]
