# Generated by Django 4.1.11 on 2023-10-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_menucards_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='menucards_en',
        ),
    ]
