# Generated by Django 4.2.7 on 2023-11-22 17:28

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_menucards_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_snipet_carusel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footer_snipet_contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='menucards1',
            field=wagtail.fields.StreamField([('cards_fild', wagtail.blocks.StructBlock([('external_url', wagtail.blocks.RichTextBlock(features=['link', 'h4'], label='ссылка на страницу с оборудованием', required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, use_json_field=True, verbose_name='Карточка меню'),
        ),
        migrations.AlterField(
            model_name='portnerurlfuter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlfooter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
