# Generated by Django 4.2.7 on 2024-03-13 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0009_alter_footer_snipet_carusel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_snipet_contact',
            name='locale',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer_snipet_contact',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='footer_snipet_contact',
            unique_together={('translation_key', 'locale')},
        ),
    ]
