# Generated by Django 4.2.7 on 2025-12-11 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_footer_snipet_contact_locale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('unique_visits', models.IntegerField(default=0, verbose_name='Уникальные посещения')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Всего посещений')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика посещений',
                'verbose_name_plural': 'Статистика посещений',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата посещения')),
                ('visit_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время посещения')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visit_datetime'],
                'indexes': [models.Index(fields=['visit_date', 'ip_address'], name='home_sitevi_visit_d_153ddc_idx'), models.Index(fields=['-visit_datetime'], name='home_sitevi_visit_d_68ae9a_idx')],
            },
        ),
    ]
