# Generated by Django 4.2.7 on 2025-12-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_visitstatistics_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активировать глобальную скидку')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Процент скидки от 0 до 100', max_digits=5, verbose_name='Процент скидки (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки скидок на оборудование',
                'verbose_name_plural': 'Настройки скидок на оборудование',
            },
        ),
    ]
