# Generated by Django 4.2.7 on 2025-12-12 11:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_banner_slider_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_slider_settings',
            field=wagtail.fields.StreamField([('banner_slider', wagtail.blocks.StructBlock([('main_title', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'bold', 'italic', 'link'], help_text='Основной заголовок сайта (отображается над слайдером)', required=False)), ('slider_text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'p', 'bold', 'italic', 'link', 'ul', 'ol'], help_text='Общий текст для всех слайдов (если не указан индивидуальный текст)', required=False)), ('background_image_1', wagtail.images.blocks.ImageChooserBlock(help_text='Фоновое изображение для слайда 1', required=False)), ('slide_text_1', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'p', 'bold', 'italic', 'link', 'ul', 'ol'], help_text='Текст для слайда 1', required=False)), ('background_image_2', wagtail.images.blocks.ImageChooserBlock(help_text='Фоновое изображение для слайда 2', required=False)), ('slide_text_2', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'p', 'bold', 'italic', 'link', 'ul', 'ol'], help_text='Текст для слайда 2', required=False)), ('background_image_3', wagtail.images.blocks.ImageChooserBlock(help_text='Фоновое изображение для слайда 3', required=False)), ('slide_text_3', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'p', 'bold', 'italic', 'link', 'ul', 'ol'], help_text='Текст для слайда 3', required=False)), ('background_image_4', wagtail.images.blocks.ImageChooserBlock(help_text='Фоновое изображение для слайда 4', required=False)), ('slide_text_4', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'p', 'bold', 'italic', 'link', 'ul', 'ol'], help_text='Текст для слайда 4', required=False)), ('background_image_5', wagtail.images.blocks.ImageChooserBlock(help_text='Фоновое изображение для слайда 5', required=False)), ('slide_text_5', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'p', 'bold', 'italic', 'link', 'ul', 'ol'], help_text='Текст для слайда 5', required=False))]))], blank=True, help_text='Настройки для слайдера на главной странице', use_json_field=True, verbose_name='Настройки слайдера'),
        ),
    ]
