# Generated by Django 4.2.7 on 2026-01-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_order_orderitem_order_home_order_created_9399f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона для связи', max_length=50, null=True, verbose_name='Номер телефона')),
                ('messenger_link', models.URLField(blank=True, help_text='Ссылка на Telegram, WhatsApp или другой мессенджер', null=True, verbose_name='Ссылка на мессенджер')),
                ('name_or_organization', models.CharField(help_text='Ваше имя или название организации', max_length=255, verbose_name='Имя или название организации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
