# Generated by Django 4.2.7 on 2026-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='promote_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ключевые слова'),
        ),
    ]
