# Generated by Django 4.2.7 on 2026-01-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_banner_slider_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Дата, на которую запланирован монтаж', null=True, verbose_name='Дата монтажа'),
        ),
        migrations.AddField(
            model_name='order',
            name='installation_time',
            field=models.TimeField(blank=True, help_text='Время начала монтажа', null=True, verbose_name='Время начала монтажа'),
        ),
    ]
