# Generated by Django 4.2.7 on 2026-01-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_add_installation_date_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['installation_date'], name='home_order_install_160d00_idx'),
        ),
    ]
