# Generated by Django 4.2.7 on 2026-01-14 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0022_add_installation_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSnippetCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_band', models.URLField(blank=True, help_text='Ссылка на группу или страницу', null=True, verbose_name='Ссылка на группу')),
                ('photo_in_carousel', models.ImageField(upload_to='carousel/', verbose_name='Фото в карусели')),
                ('interval', models.IntegerField(blank=True, help_text='Интервал переключения слайдов в миллисекундах', null=True, verbose_name='Интервал переключения')),
            ],
            options={
                'verbose_name': 'Контент карусели в футере',
                'verbose_name_plural': 'Данные карусели',
            },
        ),
        migrations.CreateModel(
            name='FooterSnippetContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url_contact_data', models.URLField(blank=True, null=True, verbose_name='URL контактных данных')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': 'Контактные данные в футере',
                'verbose_name_plural': 'Контактные данные',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='PartnerUrlFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_partner_page', models.URLField(blank=True, null=True, verbose_name='URL страницы партнера')),
                ('text_link_partner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ссылки партнера')),
                ('promo_description_partner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание партнера')),
            ],
            options={
                'verbose_name': 'Партнер в футере',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.DeleteModel(
            name='Footer_snipet_carusel',
        ),
        migrations.AlterUniqueTogether(
            name='footer_snipet_contact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footer_snipet_contact',
            name='locale',
        ),
        migrations.DeleteModel(
            name='PortnerUrlFuter',
        ),
        migrations.AlterModelOptions(
            name='urlfooter',
            options={'verbose_name': 'Полезная ссылка в футере', 'verbose_name_plural': 'Полезные ссылки'},
        ),
        migrations.RemoveField(
            model_name='urlfooter',
            name='promo_discript',
        ),
        migrations.RemoveField(
            model_name='urlfooter',
            name='url_posicion',
        ),
        migrations.AddField(
            model_name='urlfooter',
            name='promo_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='urlfooter',
            name='url_position',
            field=models.URLField(blank=True, null=True, verbose_name='URL ссылки'),
        ),
        migrations.AlterField(
            model_name='urlfooter',
            name='text_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ссылки'),
        ),
        migrations.DeleteModel(
            name='Footer_snipet_contact',
        ),
    ]
